# Generated by Django 5.1.15 on 2026-10-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationletter',
            name='check_in_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='allocationletter',
            name='check_in_verified_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='allocationletter',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationletter',
            name='is_checked_in',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='allocationletter',
            name='key_number_issued',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='allocationletter',
            name='qr_verification_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
