# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('DISTANCE', 'Minimum Distance from University (km)'), ('ACADEMIC', 'Minimum CGPA / Grade Requirement'), ('DISCIPLINARY', 'No Pending Disciplinary Record'), ('FEE_CLEARED', 'Prior Academic Fee Clearance')], max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text="Config parameters (e.g. {'min_distance_km': 30})")),
                ('is_hard_rule', models.BooleanField(default=True, help_text='If true, violation causes automatic ineligibility')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='applications.allocationcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('is_passed', models.BooleanField()),
                ('reason', models.TextField(help_text='Detailed outcome reasoning for transparent audit')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='applications.application')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility.eligibilityrule')),
            ],
            options={
                'unique_together': {('application', 'rule')},
            },
        ),
    ]
