# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('warden_id', models.CharField(max_length=64)),
                ('warden_email', models.EmailField(max_length=254)),
                ('mandatory_reason', models.TextField(help_text='Mandatory justification for warden manual reassignment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='allocation.allocationassignment')),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overridden_to', to='inventory.bed')),
                ('previous_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overridden_from', to='inventory.bed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WardenApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('warden_id', models.CharField(max_length=64)),
                ('warden_email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='allocation.allocationdraft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
