# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('priority_order', models.PositiveIntegerField(help_text='1 = Next in queue for promotion')),
                ('status', models.CharField(choices=[('ACTIVE', 'Waiting'), ('OFFERED', 'Bed Offered'), ('ACCEPTED', 'Offer Accepted'), ('EXPIRED', 'Offer Expired')], default='ACTIVE', max_length=20)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='applications.application')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='applications.allocationcycle')),
            ],
            options={
                'ordering': ['priority_order'],
                'unique_together': {('cycle', 'priority_order')},
            },
        ),
    ]
