# Generated by Django 5.1.15 on 2026-10-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bed_occupant_name_bed_occupant_student_id_and_more'),
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='offered_bed',
            field=models.ForeignKey(blank=True, help_text='Specific bed offered during dynamic vacancy promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_offers', to='inventory.bed'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if student declines offer'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Waiting in Queue'), ('OFFERED', 'Bed Offered'), ('ACCEPTED', 'Offer Accepted'), ('DECLINED', 'Offer Declined'), ('EXPIRED', 'Offer Expired')], default='ACTIVE', max_length=20),
        ),
    ]
