# Generated by Django 5.1.15 on 2026-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_fee_cleared'),
        ('inventory', '0002_bed_occupant_name_bed_occupant_student_id_and_more'),
        ('waitlist', '0002_waitlistentry_decision_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'OFFERED'])), fields=('cycle', 'priority_order'), name='unique_active_priority_per_cycle'),
        ),
    ]
