# Generated by Django 5.1.15 on 2026-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_fee_cleared'),
        ('inventory', '0002_bed_occupant_name_bed_occupant_student_id_and_more'),
        ('waitlist', '0002_waitlistentry_decision_at_and_more'),
    ]

    operations = [
        # SQLite / libSQL does not report named inline unique constraints during introspection,
        # which causes alter_unique_together to fail with ValueError: Found wrong number (0) of constraints.
        # We separate state and database operations to safely update Django's model state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='waitlistentry',
                    unique_together=set(),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS waitlist_waitlistentry_cycle_id_priority_order_uniq;",
                    reverse_sql="",
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['ACTIVE', 'OFFERED'])),
                fields=('cycle', 'priority_order'),
                name='unique_active_priority_per_cycle'
            ),
        ),
    ]
