# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = Highest preference')),
                ('preferred_room_type', models.CharField(choices=[('SINGLE', 'Single Occupancy'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('DORM', 'Dormitory')], default='DOUBLE', max_length=20)),
                ('preferred_roommate_id', models.CharField(blank=True, help_text='Mutual roommate request student ID', max_length=64, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='applications.application')),
                ('preferred_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hostel')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('application', 'rank')},
            },
        ),
    ]
