# Generated by Django 5.1.15 on 2026-10-02 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_fee_cleared'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACCEPTED', 'Mutual Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, default='', max_length=255)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to='applications.application')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
