# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('sleep_habit', models.CharField(choices=[('EARLY_BIRD', 'Early Bird (sleeps before 11 PM)'), ('NIGHT_OWL', 'Night Owl (sleeps after 1 AM)'), ('FLEXIBLE', 'Flexible / Moderate')], default='FLEXIBLE', max_length=20)),
                ('study_environment', models.CharField(choices=[('SILENT', 'Absolute Silence'), ('LIGHT_MUSIC', 'Background Music / Ambient'), ('COLLABORATIVE', 'Discussion / Group Friendly')], default='LIGHT_MUSIC', max_length=20)),
                ('cleanliness_priority', models.CharField(choices=[('VERY_STRICT', 'Very Strict / Neat Freak'), ('MODERATE', 'Moderate Daily Cleaning'), ('RELAXED', 'Casual / Relaxed')], default='MODERATE', max_length=20)),
                ('guest_tolerance_score', models.PositiveSmallIntegerField(default=3, help_text='1 (Low) to 5 (High)')),
                ('consent_recorded', models.BooleanField(default=False, help_text='DPDP Act 2023 Explicit Student Consent')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_response', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
