# Generated by Django 5.1.15 on 2026-09-23 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='occupant_name',
            field=models.CharField(blank=True, help_text='Cached name for display', max_length=120),
        ),
        migrations.AddField(
            model_name='bed',
            name='occupant_student_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hostel',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='cooling_type',
            field=models.CharField(choices=[('AC', 'Air Conditioned (AC)'), ('COOLER', 'Desert / Air Cooler'), ('NONE', 'Natural / Ceiling Fan Only')], default='COOLER', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.CharField(blank=True, default='Study Table, Wardrobe, High-Speed Wi-Fi', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, help_text='Nominal capacity; derived from beds count'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('floor_number', models.IntegerField(default=0, help_text='0=Ground, 1=1st Floor, etc.')),
                ('name', models.CharField(blank=True, help_text='e.g. Ground Floor, 1st Floor', max_length=60)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='inventory.block')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('block', 'floor_number')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.floor'),
        ),
        migrations.CreateModel(
            name='RoomChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('student_id', models.CharField(db_index=True, max_length=64)),
                ('student_name', models.CharField(max_length=120)),
                ('student_email', models.EmailField(max_length=254)),
                ('preferred_cooling', models.CharField(choices=[('AC', 'Air Conditioned (AC)'), ('COOLER', 'Desert / Air Cooler'), ('NONE', 'Natural / Ceiling Fan Only')], default='AC', max_length=10)),
                ('preferred_room_type', models.CharField(choices=[('SINGLE', 'Single Occupancy'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('DORM', 'Dormitory (4+)')], default='DOUBLE', max_length=10)),
                ('reason', models.TextField(help_text='Detailed student justification for room transfer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Warden Review'), ('APPROVED', 'Approved & Reassigned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('warden_remarks', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_new_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_to', to='inventory.bed')),
                ('current_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='inventory.bed')),
                ('requested_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardenHostelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('warden_name', models.CharField(max_length=120)),
                ('warden_email', models.EmailField(max_length=254)),
                ('assigned_by', models.CharField(default='System Administrator', max_length=120)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignment', to='inventory.hostel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
