# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('name', models.CharField(help_text='e.g. AY 2026-27 Autumn Allotment', max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('application_start', models.DateTimeField()),
                ('application_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Configuring'), ('OPEN', 'Applications Open'), ('CLOSED', 'Applications Closed'), ('PROCESSING', 'Allocation In Progress'), ('REVIEW', 'Warden Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('student_id', models.CharField(db_index=True, max_length=64)),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('programme', models.CharField(help_text='e.g. B.Tech Computer Science', max_length=100)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('requires_accessible_room', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible'), ('ALLOCATED', 'Allocated in Draft'), ('PUBLISHED', 'Published Assigned'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.allocationcycle')),
            ],
            options={
                'unique_together': {('cycle', 'student_id')},
            },
        ),
    ]
