# Generated by Django 5.1.15 on 2026-09-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, help_text='Permanent residential address'),
        ),
        migrations.AddField(
            model_name='application',
            name='cgpa',
            field=models.FloatField(default=8.0, help_text='CGPA / Academic score'),
        ),
        migrations.AddField(
            model_name='application',
            name='distance_from_campus_km',
            field=models.FloatField(default=50.0, help_text='Distance in KM for eligibility rule'),
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_disciplinary_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(default='B.Tech Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='requires_accessible_room',
            field=models.BooleanField(default=False, help_text='Wheelchair / ground floor requirement'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.CharField(db_index=True, help_text='Registration Number (e.g. 123001)', max_length=64),
        ),
    ]
