# Generated by Django 5.1.15 on 2026-10-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_address_application_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fee_cleared',
            field=models.BooleanField(default=True, help_text='Prior Academic & Mess Dues Cleared'),
        ),
    ]
