# Generated by Django 5.1.15 on 2026-09-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('run_identifier', models.CharField(max_length=64, unique=True)),
                ('random_seed', models.PositiveIntegerField(default=42, help_text='Stored seed ensures 100% reproducible tiebreaks')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Solving / Computing'), ('COMPLETED', 'Draft Generated'), ('REVIEWED', 'Warden Reviewed'), ('PUBLISHED', 'Published Final'), ('FAILED', 'Run Failed')], default='IN_PROGRESS', max_length=20)),
                ('total_applicants', models.PositiveIntegerField(default=0)),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('unassigned_count', models.PositiveIntegerField(default=0)),
                ('summary_metrics', models.JSONField(blank=True, default=dict)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='applications.allocationcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('preference_rank_honoured', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(help_text='Detailed explanation of why this bed was allocated')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='applications.application')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.bed')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='allocation.allocationdraft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'bed'), name='unique_bed_per_draft'), models.UniqueConstraint(fields=('draft', 'application'), name='unique_application_per_draft')],
            },
        ),
    ]
