# Generated by Django 5.1.15 on 2026-09-30 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
        ('applications', '0002_application_address_application_cgpa_and_more'),
        ('inventory', '0002_bed_occupant_name_bed_occupant_student_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSimulationScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('name', models.CharField(default='Scenario Snapshot', max_length=150)),
                ('seed', models.PositiveIntegerField(default=88213)),
                ('pref_weight', models.PositiveSmallIntegerField(default=65)),
                ('comp_weight', models.PositiveSmallIntegerField(default=35)),
                ('reserved_quota', models.PositiveSmallIntegerField(default=15)),
                ('hypo_block', models.CharField(blank=True, max_length=64)),
                ('hypo_cooling', models.CharField(blank=True, max_length=64)),
                ('excluded_blocks', models.JSONField(blank=True, default=list)),
                ('result_metrics', models.JSONField(blank=True, default=dict)),
                ('simulated_allocations', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_simulations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_simulations', to='applications.allocationcycle')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_simulations', to='inventory.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
