# Generated by Django 5.1.15 on 2026-09-22 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.CharField(db_index=True, default='inst_default', help_text='Tenant institution identifier', max_length=64)),
                ('actor_id', models.CharField(blank=True, help_text='User ID or System Worker', max_length=128, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(help_text='e.g. ALLOCATION_RUN, OVERRIDE, PUBLISH', max_length=64)),
                ('target_entity', models.CharField(help_text='Model/Resource name', max_length=64)),
                ('target_id', models.CharField(help_text='Primary key of target', max_length=64)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Mandatory for overrides and manual interventions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
